# coding: utf-8

"""
    bl-db-product

    This is a API document for Product DB

    OpenAPI spec version: 0.0.1
    Contact: master@bluehack.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.update_product_response import UpdateProductResponse


class TestUpdateProductResponse(unittest.TestCase):
    """ UpdateProductResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateProductResponse(self):
        """
        Test UpdateProductResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.update_product_response.UpdateProductResponse()
        pass


if __name__ == '__main__':
    unittest.main()
