# coding: utf-8

"""
    bl-db-product

    This is a API document for Product DB

    OpenAPI spec version: 0.0.1
    Contact: master@bluehack.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.get_version_response import GetVersionResponse


class TestGetVersionResponse(unittest.TestCase):
    """ GetVersionResponse unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetVersionResponse(self):
        """
        Test GetVersionResponse
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.get_version_response.GetVersionResponse()
        pass


if __name__ == '__main__':
    unittest.main()
